Workflows - e2e dependencies

diff --git a/.github/workflows/deploy-template.yml b/.github/workflows/deploy-template.yml
--- a/.github/workflows/deploy-template.yml
+++ b/.github/workflows/deploy-template.yml
@@ -83,6 +83,7 @@ jobs:
 
   e2e-tests:
     if: ${{ vars.RUN_E2E == 'true' && inputs.environment == vars.ACTIVE_ENVIRONMENT }}
+    needs: terraform-plan
     runs-on: ubuntu-latest
     permissions:
       id-token: write
@@ -96,6 +97,16 @@ jobs:
           aws-region: eu-west-2
           role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/auto-ops
           role-session-name: github-actions
+
+      - uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: "1.12.2"
+
+      - name: Terraform Init
+        working-directory: ${{ vars.TERRAFORM_DIR_PATH }}
+        run: |
+          export BUCKET_NAME=${{ vars.TERRAFORM_STATE_BUCKET_NAME_INT }}
+          make init environment=${{ inputs.environment }} aws_account_name=${{ inputs.aws_account_name }}
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -125,30 +136,29 @@ jobs:
         env:
           APIGEE_USERNAME: ${{ vars.APIGEE_USERNAME }}
           APIGEE_PASSWORD: ${{ secrets.APIGEE_PASSWORD }}
-          MFA_CODE: ${{ env.MFA_CODE }}
           APIGEE_OAUTH_TOKEN: ${{ secrets.APIGEE_OAUTH_TOKEN }}
-          OTP_SECRET: ${{ secrets.APIGEE_OTP_KEY }}
+          APIGEE_OTP_SECRET: ${{ secrets.APIGEE_OTP_KEY }}
         run: |
-            CODE=$(oathtool --totp -b "$OTP_SECRET")
-            echo "::add-mask::$CODE"
+          CODE=$(oathtool --totp -b "$APIGEE_OTP_SECRET")
+          echo "::add-mask::$CODE"
 
-            echo "Requesting access token from Apigee..."
+          echo "Requesting access token from Apigee..."
 
-            response=$(curl -s -X POST "https://login.apigee.com/oauth/token" \
-              -H "Content-Type: application/x-www-form-urlencoded" \
-              -H "Accept: application/json;charset=utf-8" \
-              -H "Authorization: Basic $APIGEE_OAUTH_TOKEN" \
-              -d "username=$APIGEE_USERNAME&password=$APIGEE_PASSWORD&mfa_token=$CODE&grant_type=password")
+          response=$(curl -s -X POST "https://login.apigee.com/oauth/token" \
+            -H "Content-Type: application/x-www-form-urlencoded" \
+            -H "Accept: application/json;charset=utf-8" \
+            -H "Authorization: Basic $APIGEE_OAUTH_TOKEN" \
+            -d "username=$APIGEE_USERNAME&password=$APIGEE_PASSWORD&mfa_token=$CODE&grant_type=password")
 
-            token=$(echo "$response" | jq -r '.access_token // empty')
+          token=$(echo "$response" | jq -r '.access_token // empty')
 
-            if [[ -z "$token" ]]; then
-              echo "Failed to retrieve access token"
-              exit 1
-            fi
+          if [[ -z "$token" ]]; then
+            echo "Failed to retrieve access token"
+            exit 1
+          fi
 
-            echo "::add-mask::$token"
-            echo "APIGEE_ACCESS_TOKEN=$token" >> $GITHUB_ENV
+          echo "::add-mask::$token"
+          echo "APIGEE_ACCESS_TOKEN=$token" >> $GITHUB_ENV
 
       - name: Run e2e tests
         working-directory: ${{ vars.E2E_DIR_PATH }}
