init I

diff --git a/.github/workflows/quality-checks.yml b/.github/workflows/quality-checks.yml
--- a/.github/workflows/quality-checks.yml
+++ b/.github/workflows/quality-checks.yml
@@ -97,17 +97,6 @@ jobs:
           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
 
-      - name: Run unittest with batchprocessorfilter-coverage
-        working-directory: batch_processor_filter
-        id: batchprocessorfilter
-        env:
-          PYTHONPATH: ${{ github.workspace }}/batch_processor_filter/src:${{ github.workspace }}/batch_processor_filter/tests
-        continue-on-error: true
-        run: |
-          poetry install
-          poetry run coverage run -m unittest discover || echo "batchprocessorfilter tests failed" >> ../failed_tests.txt
-          poetry run coverage xml -o ../batchprocessorfilter-coverage.xml
-
       - name: Run unittest with recordprocessor-coverage
         working-directory: lambdas/recordprocessor
         id: recordprocessor
@@ -161,6 +150,17 @@ jobs:
           poetry install
           poetry run coverage run --source=src -m unittest discover || echo "ack-lambda tests failed" >> ../../failed_tests.txt
           poetry run coverage xml -o ../../ack-lambda-coverage.xml
+
+      - name: Run unittest with batchprocessorfilter-coverage
+        working-directory: lambdas/batch_processor_filter
+        id: batchprocessorfilter
+        env:
+          PYTHONPATH: ${{ env.LAMBDA_PATH }}/batch_processor_filter/src:${{ env.LAMBDA_PATH }}/batch_processor_filter/tests:${{ env.SHARED_PATH }}/src
+        continue-on-error: true
+        run: |
+          poetry install
+          poetry run coverage run -m unittest discover || echo "batchprocessorfilter tests failed" >> ../../failed_tests.txt
+          poetry run coverage xml -o ../../batchprocessorfilter-coverage.xml
 
       - name: Run unittest with coverage-delta
         working-directory: lambdas/delta_backend
