init

diff --git a/.github/workflows/quality-checks.yml b/.github/workflows/quality-checks.yml
--- a/.github/workflows/quality-checks.yml
+++ b/.github/workflows/quality-checks.yml
@@ -140,17 +140,6 @@ jobs:
           poetry run coverage run -m unittest discover -p "*batch*.py" || echo "recordforwarder tests failed" >> ../failed_tests.txt
           poetry run coverage xml -o ../recordforwarder-coverage.xml
 
-      - name: Run unittest with coverage-delta
-        working-directory: delta_backend
-        id: delta
-        env:
-          PYTHONPATH: delta_backend/src:delta_backend/tests
-        continue-on-error: true
-        run: |
-          poetry install
-          poetry run coverage run -m unittest discover || echo "delta tests failed" >> ../failed_tests.txt
-          poetry run coverage xml -o ../delta-coverage.xml
-
       - name: Run unittest with coverage-fhir-api
         working-directory: backend
         env:
@@ -181,6 +170,17 @@ jobs:
           poetry install
           poetry run coverage run --source=src -m unittest discover || echo "ack-lambda tests failed" >> ../../failed_tests.txt
           poetry run coverage xml -o ../../ack-lambda-coverage.xml
+
+      - name: Run unittest with coverage-delta
+        working-directory: lambdas/delta_backend
+        id: delta
+        env:
+          PYTHONPATH: ${{ env.LAMBDA_PATH }}/delta_backend/src:${{ env.LAMBDA_PATH }}/delta_backend/tests:${{ env.SHARED_PATH }}/src
+        continue-on-error: true
+        run: |
+          poetry install
+          poetry run coverage run -m unittest discover || echo "delta tests failed" >> ../../failed_tests.txt
+          poetry run coverage xml -o ../../delta-coverage.xml
 
       - name: Run unittest with coverage-mns-subscription
         working-directory: lambdas/mns_subscription
