VED-788 Refactor ack_backend (#844)
* init

* lint

* smells

* typo

* imports

* cleanup

* sonarcloud

* sonarcloud II

* local Makefile

* tests for get_s3_client

* tests for get_s3_client II

* delete .coverage

* use_ms_precision

* lint

* shared helper functions

* prefix

* missing cache tests

* test_errors

* terraform fixes per VED-810

* review fixes

* review fixes II

* review fixes III

diff --git a/.github/workflows/quality-checks.yml b/.github/workflows/quality-checks.yml
--- a/.github/workflows/quality-checks.yml
+++ b/.github/workflows/quality-checks.yml
@@ -106,17 +106,6 @@ jobs:
           poetry run coverage run -m unittest discover -p "*batch*.py" || echo "recordforwarder tests failed" >> ../failed_tests.txt
           poetry run coverage xml -o ../recordforwarder-coverage.xml
 
-      - name: Run unittest with coverage-ack-lambda
-        working-directory: ack_backend
-        id: acklambda
-        env:
-          PYTHONPATH: ${{ github.workspace }}/ack_backend/src:${{ github.workspace }}/ack_backend/tests
-        continue-on-error: true
-        run: |
-          poetry install
-          poetry run coverage run -m unittest discover || echo "ack-lambda tests failed" >> ../failed_tests.txt
-          poetry run coverage xml -o ../ack-lambda-coverage.xml
-
       - name: Run unittest with coverage-delta
         working-directory: delta_backend
         id: delta
@@ -147,6 +136,17 @@ jobs:
           poetry install
           poetry run coverage run -m unittest discover || echo "mesh_processor tests failed" >> ../failed_tests.txt
           poetry run coverage xml -o ../mesh_processor-coverage.xml
+
+      - name: Run unittest with coverage-ack-lambda
+        working-directory: lambdas/ack_backend
+        id: acklambda
+        env:
+          PYTHONPATH: ${{ env.LAMBDA_PATH }}/ack_backend/src:${{ github.workspace }}/ack_backend/tests
+        continue-on-error: true
+        run: |
+            poetry install
+            poetry run coverage run --source=src -m unittest discover || echo "ack-lambda tests failed" >> ../../failed_tests.txt
+            poetry run coverage xml -o ../../ack-lambda-coverage.xml
 
       - name: Run unittest with coverage-mns-subscription
         working-directory: lambdas/mns_subscription
