Formatting and linting improvements. (#887)
* Add black for code formatting. Remove some linting exclusions. Fix errors.

* Fix path.

* Don't install quality_checks package.

* Fix commands.

* Update pre-commit script.

* Add lint-staged to lint and format staged files only.

* Add husky to manage commit hooks.

* Add prettier for MD / YAML / JSON formatting.

* Resolve some Sonar warnings.

* Add .prettierignore and run prettier on all supported files.

* Revert auto formatting of jsc files.

* Fix lint error.

* Format Terraform.

diff --git a/.github/workflows/quality-checks.yml b/.github/workflows/quality-checks.yml
--- a/.github/workflows/quality-checks.yml
+++ b/.github/workflows/quality-checks.yml
@@ -12,8 +12,26 @@ env:
   LAMBDA_PATH: ${{ github.workspace }}/lambdas
 
 jobs:
-  lint:
-    name: Lint specification and Python projects
+  lint-specification:
+    name: Lint specification
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v5
+
+      - uses: actions/setup-node@v5
+        with:
+          node-version: "23.11.0"
+          cache: "npm"
+
+      - name: Install linting dependencies
+        run: make install-node
+
+      - name: Lint
+        run: make lint
+
+  lint-python:
+    name: Lint Python projects
     runs-on: ubuntu-latest
 
     steps:
@@ -22,23 +40,22 @@ jobs:
       - name: Install poetry
         run: pip install poetry==2.1.4
 
-      # Base linting requires 3.8 due to APIM package dependencies. See root README for details under linting.
-      # Consider upgrading this and poetry deps if we move away from Azure DevOps to using the Proxygen tool.
       - uses: actions/setup-python@v6
         with:
-          python-version: 3.8
-          cache: 'poetry'
-
-      - uses: actions/setup-node@v5
-        with:
-          node-version: '23.11.0'
-          cache: 'npm'
+          python-version: 3.11
+          cache: "poetry"
 
       - name: Install linting dependencies
-        run: make install-node && poetry install --no-root
+        run: poetry install --no-root
+        working-directory: quality_checks
 
       - name: Lint
-        run: make lint
+        run: poetry run make lint
+        working-directory: quality_checks
+
+      - name: Check formatting
+        run: poetry run make format-check
+        working-directory: quality_checks
 
   testcoverage_and_sonarcloud:
     name: Test Coverage and SonarCloud
@@ -53,7 +70,7 @@ jobs:
       - uses: actions/setup-python@v6
         with:
           python-version: 3.11
-          cache: 'poetry'
+          cache: "poetry"
 
       - name: Set up AWS credentials
         env:
@@ -110,7 +127,7 @@ jobs:
         working-directory: delta_backend
         id: delta
         env:
-            PYTHONPATH: delta_backend/src:delta_backend/tests
+          PYTHONPATH: delta_backend/src:delta_backend/tests
         continue-on-error: true
         run: |
           poetry install
@@ -144,9 +161,9 @@ jobs:
           PYTHONPATH: ${{ env.LAMBDA_PATH }}/ack_backend/src:${{ github.workspace }}/ack_backend/tests
         continue-on-error: true
         run: |
-            poetry install
-            poetry run coverage run --source=src -m unittest discover || echo "ack-lambda tests failed" >> ../../failed_tests.txt
-            poetry run coverage xml -o ../../ack-lambda-coverage.xml
+          poetry install
+          poetry run coverage run --source=src -m unittest discover || echo "ack-lambda tests failed" >> ../../failed_tests.txt
+          poetry run coverage xml -o ../../ack-lambda-coverage.xml
 
       - name: Run unittest with coverage-mns-subscription
         working-directory: lambdas/mns_subscription
