VED-714 rearchitect to prevent batch race conditions (#770)

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -46,9 +46,22 @@ jobs:
           poetry run coverage run -m unittest discover || echo "filenameprocessor tests failed" >> ../failed_tests.txt
           poetry run coverage xml -o ../filenameprocessor-coverage.xml
 
+      - name: Run unittest with batchprocessorfilter-coverage
+        working-directory: batch_processor_filter
+        id: batchprocessorfilter
+        env:
+          PYTHONPATH: ${{ github.workspace }}/batch_processor_filter/src:${{ github.workspace }}/batch_processor_filter/tests
+        continue-on-error: true
+        run: |
+          poetry install
+          poetry run coverage run -m unittest discover || echo "batchprocessorfilter tests failed" >> ../failed_tests.txt
+          poetry run coverage xml -o ../batchprocessorfilter-coverage.xml
+
       - name: Run unittest with recordprocessor-coverage
         working-directory: recordprocessor
         id: recordprocessor
+        env:
+          PYTHONPATH: ${{ github.workspace }}/recordprocessor/src:${{ github.workspace }}/recordprocessor/tests
         continue-on-error: true
         run: |
           poetry install
