debug

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -138,8 +138,8 @@ jobs:
             echo "shared coverage - Current directory: $(pwd)"
             poetry env use 3.11
             poetry install
-            poetry run coverage run -m unittest discover || echo "shared tests failed" >> ../failed_tests.txt
-            poetry run coverage xml -o ../shared-coverage.xml
+            poetry run coverage run -m unittest discover || echo "shared tests failed" >> ../../failed_tests.txt
+            poetry run coverage xml -o ../../shared-coverage.xml
 
       - name: Run unittest with id_sync
         working-directory: lambdas/id_sync
@@ -151,12 +151,18 @@ jobs:
             echo "id_sync coverage - Current directory: $(pwd)"
             poetry env use 3.11
             poetry install
-            poetry run coverage run -m unittest discover || echo "id_sync tests failed" >> ../failed_tests.txt
-            poetry run coverage xml -o ../id_sync-coverage.xml
+            poetry run coverage run -m unittest discover || echo "id_sync tests failed" >> ../../failed_tests.txt
+            poetry run coverage xml -o ../../id_sync-coverage.xml
+            #check files created
+            if [ ! -f ../../id_sync-coverage.xml ]; then
+              echo "id_sync-coverage.xml not found, exiting with error"
+            fi
 
       - name: Run Test Failure Summary
         id: check_failure
         run: |
+          echo "Checking for test failures..."
+          ls *-coverage.xml
           if [ -s failed_tests.txt ]; then
             echo "The following tests failed:"
             cat failed_tests.txt
