Update tests

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -12,6 +12,9 @@ jobs:
     name: SonarCloud
     if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependency') }}
     runs-on: ubuntu-latest
+
+    continue-on-error: true
+    
     steps:
       - uses: actions/checkout@v4
         with:
@@ -27,14 +30,16 @@ jobs:
         
           
       - name: Run unittest with filenameprocessor-coverage
+        id: filenameprocessor
         run: |
-          pip install poetry==1.8.2 moto==4.2.11 coverage redis botocore==1.35.49 simplejson pandas freezegun
+          pip install poetry==1.8.4 moto==4.2.11 coverage redis botocore==1.35.49 simplejson pandas freezegun
           poetry run coverage run --source=filenameprocessor -m unittest discover -s filenameprocessor
           poetry run coverage xml -o sonarcloud-coverage-filenameprocessor-coverage.xml
         continue-on-error: true
 
       
       - name: Run unittest with recordprocessor-coverage
+        id: recordprocessor
         continue-on-error: true
         run: |
           poetry run coverage run --source=recordprocessor -m unittest discover -s recordprocessor
@@ -42,32 +47,41 @@ jobs:
 
 
       - name: Run unittest with recordforwarder-coverage
+        id: recordforwarder
         continue-on-error: true
         run: |
-          poetry run coverage run --source=recordforwarder -m unittest discover -s recordforwarder
+          poetry run coverage run --source=backend -m unittest discover -s backend/tests -p "*batch*.py"
           poetry run coverage xml -o sonarcloud-coverage-recordforwarder-coverage.xml
 
           
       - name: Run unittest with coverage-ack-lambda
+        id: acklambda
         continue-on-error: true
         run: |
-          pip install poetry coverage moto==4.2.11 freezegun
+          pip install poetry==1.8.4 coverage moto==4.2.11 freezegun
           poetry run coverage run --source=ack_backend -m unittest discover -s ack_backend
           poetry run coverage xml -o sonarcloud-coverage-ack-lambda.xml
 
       - name: Run unittest with coverage-delta
+        id: delta
         continue-on-error: true
         run: |
-          pip install poetry mypy-boto3-dynamodb==1.35.54 boto3==1.26.165 coverage botocore==1.29.165 jmespath==1.0.1 python-dateutil==2.9.0 urllib3==1.26.20 s3transfer==0.6.2 typing-extensions==4.12.2
+          pip install poetry==1.8.4 mypy-boto3-dynamodb==1.35.54 boto3==1.26.165 coverage botocore==1.29.165 jmespath==1.0.1 python-dateutil==2.9.0 urllib3==1.26.20 s3transfer==0.6.2 typing-extensions==4.12.2
           poetry run coverage run --source=delta_backend -m unittest discover -s delta_backend
           poetry run coverage xml -o sonarcloud-coverage-delta.xml
       
       - name: Run unittest with coverage-fhir-api
+        id: fhirapi
         continue-on-error: true
         run: |
-          pip install poetry moto==4.2.11 coverage redis botocore==1.35.49 simplejson responses structlog fhir.resources jsonpath_ng pydantic==1.10.13 requests aws-lambda-typing cffi pyjwt boto3-stubs-lite[dynamodb]~=1.26.90 python-stdnum==1.20
+          pip install poetry==1.8.4 moto==4.2.11 coverage redis botocore==1.35.49 simplejson responses structlog fhir.resources jsonpath_ng pydantic==1.10.13 requests aws-lambda-typing cffi pyjwt boto3-stubs-lite[dynamodb]~=1.26.90 python-stdnum==1.20
           poetry run coverage run --source=backend -m unittest discover -s backend
           poetry run coverage xml -o sonarcloud-coverage.xml
+
+      -name: Determine Test success or failure
+        run: |
+        if["${{ steps.filenameprocessor.outcome}}" != "success"]: then echo "filenameprocessor failed"; exit 1; fi
+        if["${{ steps.recordprocessor.outcome}}" != "success"]: then echo "recordprocessor failed"; exit 1; fi
 
 
       - name: SonarCloud Scan
