test failure update

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -27,14 +27,14 @@ jobs:
           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
       
-      - name: Initialize Failure Tracker
+      - name: Initialize Unit Test Failure Tracker
         run: echo "false" > test_failed.txt
           
       - name: Run unittest with filenameprocessor-coverage
         id: filenameprocessor
         run: |
           pip install poetry==1.8.4 moto==4.2.11 coverage redis botocore==1.35.49 simplejson pandas freezegun
-          poetry run coverage run --source=filenameprocessor -m unittest discover -s filenameprocessor
+          poetry run coverage run --source=filenameprocessor -m unittest discover -s filenameprocessor || echo "filenameprocessor tests failed" >> failed_tests.txt
           poetry run coverage xml -o sonarcloud-coverage-filenameprocessor-coverage.xml
         continue-on-error: true
 
@@ -43,7 +43,7 @@ jobs:
         id: recordprocessor
         continue-on-error: true
         run: |
-          poetry run coverage run --source=recordprocessor -m unittest discover -s recordprocessor
+          poetry run coverage run --source=recordprocessor -m unittest discover -s recordprocessor || echo "recordprocessor tests failed" >> failed_tests.txt
           poetry run coverage xml -o sonarcloud-coverage-recordprocessor-coverage.xml
 
 
@@ -51,7 +51,7 @@ jobs:
         id: recordforwarder
         continue-on-error: true
         run: |
-          poetry run coverage run --source=backend -m unittest discover -s backend/tests -p "*batch*.py"
+          poetry run coverage run --source=backend -m unittest discover -s backend/tests -p "*batch*.py" || echo "recordforwarder tests failed" >> failed_tests.txt
           poetry run coverage xml -o sonarcloud-coverage-recordforwarder-coverage.xml
 
           
@@ -60,7 +60,7 @@ jobs:
         continue-on-error: true
         run: |
           pip install poetry==1.8.4 coverage moto==4.2.11 freezegun
-          poetry run coverage run --source=ack_backend -m unittest discover -s ack_backend || echo "true" > test_failed.txt
+          poetry run coverage run --source=ack_backend -m unittest discover -s ack_backend || echo "ack-lambda tests failed" >> failed_tests.txt
           poetry run coverage xml -o sonarcloud-coverage-ack-lambda.xml
 
       - name: Run unittest with coverage-delta
@@ -68,7 +68,7 @@ jobs:
         continue-on-error: true
         run: |
           pip install poetry==1.8.4 mypy-boto3-dynamodb==1.35.54 boto3==1.26.165 coverage botocore==1.29.165 jmespath==1.0.1 python-dateutil==2.9.0 urllib3==1.26.20 s3transfer==0.6.2 typing-extensions==4.12.2
-          poetry run coverage run --source=delta_backend -m unittest discover -s delta_backend
+          poetry run coverage run --source=delta_backend -m unittest discover -s delta_backend || echo "delta tests failed" >> failed_tests.txt
           poetry run coverage xml -o sonarcloud-coverage-delta.xml
       
       - name: Run unittest with coverage-fhir-api
@@ -76,18 +76,8 @@ jobs:
         continue-on-error: true
         run: |
           pip install poetry==1.8.4 moto==4.2.11 coverage redis botocore==1.35.49 simplejson responses structlog fhir.resources jsonpath_ng pydantic==1.10.13 requests aws-lambda-typing cffi pyjwt boto3-stubs-lite[dynamodb]~=1.26.90 python-stdnum==1.20
-          poetry run coverage run --source=backend -m unittest discover -s backend || echo "true" > test_failed.txt
+          poetry run coverage run --source=backend -m unittest discover -s backend || echo "fhir-api tests failed" >> failed_tests.txt
           poetry run coverage xml -o sonarcloud-coverage.xml
-
-      - name: Check for Test Failures
-        id: check_failure
-        run: |
-          if grep -q "true" test_failed.txt; then
-            echo "Some tests failed."
-            exit 1
-          else
-            echo "All tests passed."
-          fi
 
 
       - name: SonarCloud Scan
@@ -95,3 +85,14 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+      - name: Run Test Failure Summary
+        id: check_failure
+        run: |
+          if [ -s failed_tests.txt ]; then
+            echo "The following tests failed:"
+            cat failed_tests.txt
+            exit 1
+          else
+            echo "All tests passed."
+          fi
