common.clients
toml

sonarqube shared path

id sync path

sonarQube

duplicate ignore

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -7,6 +7,10 @@ on:
   pull_request:
     types: [labeled, opened, synchronize, reopened, unlabeled]
 
+env:
+  SHARED_PATH: ${{ github.workspace }}/lambdas/shared/src:${{ github.workspace }}/lambdas/shared/tests
+  LAMBDA_PATH: ${{ github.workspace }}/lambdas
+
 jobs:
   sonarcloud:
     name: SonarCloud
@@ -26,6 +30,11 @@ jobs:
             3.10
             3.11
           cache: 'poetry'
+      - name: Debug shared folder
+        run: |
+          echo "Showing shared/src/common structure:"
+          ls
+          ls -R lambdas/shared/src/common || echo "Directory missing"
 
       - name: Set up AWS credentials
         env:
@@ -124,11 +133,23 @@ jobs:
             poetry run coverage run -m unittest discover || echo "redis_sync tests failed" >> ../failed_tests.txt
             poetry run coverage xml -o ../redis_sync-coverage.xml
 
+      - name: Run unittest with shared
+        working-directory: lambdas/shared
+        id: shared
+        env:
+          PYTHONPATH: ${{ env.SHARED_PATH }}
+        continue-on-error: true
+        run: |
+            poetry env use 3.11
+            poetry install
+            poetry run coverage run -m unittest discover || echo "shared tests failed" >> ../../failed_tests.txt
+            poetry run coverage xml -o ../../shared-coverage.xml
+
       - name: Run unittest with id_sync
         working-directory: lambdas/id_sync
         id: id_sync
         env:
-          PYTHONPATH: ${{ github.workspace }}/lambdas/id_sync/src:${{ github.workspace }}/lambdas/id_sync/tests
+          PYTHONPATH: ${{ env.LAMBDA_PATH }}/id_sync/src:${{ env.LAMBDA_PATH }}/id_sync/tests:${{ env.SHARED_PATH }}
         continue-on-error: true
         run: |
             poetry env use 3.11
