test

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -61,11 +61,14 @@ jobs:
 
       - name: Run unittest with coverage-delta
         id: delta
+        env:
+          PYTHONPATH: ./src:./tests
         continue-on-error: true
         run: |
+          echo ">>>>  >>>>  current working folder: $pwd"
           pip install poetry==1.8.4 moto==4.2.11 mypy-boto3-dynamodb==1.35.54 boto3==1.26.165 coverage botocore==1.29.165 jmespath==1.0.1 python-dateutil==2.9.0 urllib3==1.26.20 s3transfer==0.6.2 typing-extensions==4.12.2
           export PYTHONPATH=./src:./tests
-          PYTHONPATH=delta_backend/src:delta_backend/tests poetry run coverage run --source=delta_backend -m unittest discover -s delta_backend || echo "delta tests failed" >> failed_tests.txt
+          PYTHONPATH=delta_backend/src:delta_backend/tests:./src:./tests poetry run coverage run --source=delta_backend -m unittest discover -s delta_backend || echo "delta tests failed" >> failed_tests.txt
           poetry run coverage xml -o sonarcloud-coverage-delta.xml
 
       # - name: Run unittest with coverage-fhir-api
