sonarcloud test failure

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -26,7 +26,9 @@ jobs:
         run: |
           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
-        
+      
+      - name: Initialize Failure Tracker
+        run: echo "false" > test_failed.txt
           
       - name: Run unittest with filenameprocessor-coverage
         id: filenameprocessor
@@ -58,7 +60,7 @@ jobs:
         continue-on-error: true
         run: |
           pip install poetry==1.8.4 coverage moto==4.2.11 freezegun
-          poetry run coverage run --source=ack_backend -m unittest discover -s ack_backend
+          poetry run coverage run --source=ack_backend -m unittest discover -s ack_backend || echo "true" > test_failed.txt
           poetry run coverage xml -o sonarcloud-coverage-ack-lambda.xml
 
       - name: Run unittest with coverage-delta
@@ -74,9 +76,18 @@ jobs:
         continue-on-error: true
         run: |
           pip install poetry==1.8.4 moto==4.2.11 coverage redis botocore==1.35.49 simplejson responses structlog fhir.resources jsonpath_ng pydantic==1.10.13 requests aws-lambda-typing cffi pyjwt boto3-stubs-lite[dynamodb]~=1.26.90 python-stdnum==1.20
-          poetry run coverage run --source=backend -m unittest discover -s backend
+          poetry run coverage run --source=backend -m unittest discover -s backend || echo "true" > test_failed.txt
           poetry run coverage xml -o sonarcloud-coverage.xml
 
+      - name: Check for Test Failures
+        id: check_failure
+        run: |
+          if grep -q "true" test_failed.txt; then
+            echo "Some tests failed."
+            exit 1
+          else
+            echo "All tests passed."
+          fi
 
 
       - name: SonarCloud Scan
