WIP baseline

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -108,6 +108,22 @@ jobs:
           poetry run coverage run -m unittest discover || echo "mesh_processor tests failed" >> ../failed_tests.txt
           poetry run coverage xml -o ../sonarcloud-mesh_processor-coverage.xml
 
+      - name: Run unittest with redis_sync
+        working-directory: redis_sync
+        id: redis_sync
+        env:
+            PYTHONPATH: redis_sync/src:redis_sync/tests:src:tests
+        continue-on-error: true
+        run: |
+            poetry env use 3.11
+            export PYTHONPATH=$(pwd)/redis_sync/src:$(pwd)/redis_sync/tests:$(pwd)/src:$(pwd)/tests
+            echo "PYTHONPATH is set to: $PYTHONPATH"
+            echo "Running tests in redis_sync directory"
+            echo "Current working directory: $(pwd)"
+            poetry install
+            poetry run coverage run -m unittest discover || echo "redis_sync tests failed" >> ../failed_tests.txt
+            poetry run coverage xml -o ../sonarcloud-redis_sync-coverage.xml
+
       - name: Run Test Failure Summary
         id: check_failure
         run: |
