basic lambda

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -124,6 +124,18 @@ jobs:
             poetry run coverage run -m unittest discover || echo "redis_sync tests failed" >> ../failed_tests.txt
             poetry run coverage xml -o ../redis_sync-coverage.xml
 
+      - name: Run unittest with id_sync
+        working-directory: id_sync
+        id: id_sync
+        env:
+          PYTHONPATH: ${{ github.workspace }}/id_sync/src:${{ github.workspace }}/id_sync/tests
+        continue-on-error: true
+        run: |
+            poetry env use 3.11
+            poetry install
+            poetry run coverage run -m unittest discover || echo "id_sync tests failed" >> ../failed_tests.txt
+            poetry run coverage xml -o ../id_sync-coverage.xml
+
       - name: Run Test Failure Summary
         id: check_failure
         run: |
