2 Jun

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -16,9 +16,8 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: ['3.10', '3.11']
+        python-version: ['3.11', '3.10']
 
-        
     steps:
       - uses: actions/checkout@v4
         with:
@@ -29,8 +28,28 @@ jobs:
 
       - uses: actions/setup-python@v5
         with:
-          python-version: ${{ matrix.python-version }}
+          python-version: |
+            3.10
+            3.11
           cache: 'poetry'
+
+      - name: Cache global Poetry virtualenvs
+
+        # uses: actions/cache@v4
+        # with:
+        #   path: ~/.cache/pypoetry/virtualenvs
+        #   key: ${{ runner.os }}-poetry-global-venv-py${{ matrix.python-version || 'all' }}-${{ hashFiles('**/poetry.lock') }}
+        #   restore-keys: |
+        #     ${{ runner.os }}-poetry-global-venv-py${{ matrix.python-version || 'all' }}-
+
+        uses: actions/cache@v4
+        with:
+          path: ~/.cache/pypoetry/virtualenvs
+          key: ${{ runner.os }}-poetry-venv-${{ matrix.python-version }}-${{ hashFiles('<project>/poetry.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-poetry-venv-${{ matrix.python-version }}-
+
+
 
       - name: Set up AWS credentials
         env:
@@ -40,87 +59,44 @@ jobs:
           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
 
-      - name: Chmod .github directory
-        run: |
-          chmod +x $SCRIPT_FOLDER/*.sh
+      # - name: Run unittest with filenameprocessor-coverage
+      #   working-directory: filenameprocessor
+      #   id: filenameprocessor
+      #   continue-on-error: true
+      #   run: |
+      #     poetry env use 3.10
+      #     poetry install
+      #     poetry run coverage run -m unittest discover || echo "filenameprocessor tests failed" >> ../failed_tests.txt
+      #     poetry run coverage xml -o ../sonarcloud-coverage-filenameprocessor-coverage.xml
 
-      - name: Set Poetry to use in-project venvs
-        run: poetry config virtualenvs.in-project true
+      # - name: Run unittest with recordprocessor-coverage
+      #   working-directory: recordprocessor
+      #   id: recordprocessor
+      #   continue-on-error: true
+      #   run: |
+      #     poetry env use 3.10
+      #     poetry install
+      #     poetry run coverage run -m unittest discover || echo "recordprocessor tests failed" >> ../failed_tests.txt
+      #     poetry run coverage xml -o ../sonarcloud-coverage-recordprocessor-coverage.xml
 
-      - name: Cache Poetry virtualenv (filenameprocessor)
-        if: matrix.python-version == '3.10'
-        uses: actions/cache@v4
-        with:
-          path: ./filenameprocessor/.venv
-          key: ${{ runner.os }}-venv-fp-py3.10-${{ hashFiles('filenameprocessor/poetry.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-venv-fp-py3.10-
-
-      - name: Cache Poetry virtualenv (recordprocessor)
-        if: matrix.python-version == '3.10'
-        uses: actions/cache@v4
-        with:
-          path: ./recordprocessor/.venv
-          key: ${{ runner.os }}-venv-rp-py3.10-${{ hashFiles('recordprocessor/poetry.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-venv-rp-py3.10-
-
-      - name: Cache Poetry virtualenv (recordforwarder)
-        if: matrix.python-version == '3.11'
-        uses: actions/cache@v4
-        with:
-          path: ./backend/.venv
-          key: ${{ runner.os }}-venv-be-py3.11-${{ hashFiles('backend/poetry.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-venv-be-py3.11-
-
-      - name: Cache Poetry virtualenv (ack_backend)
-        if: matrix.python-version == '3.10'
-        uses: actions/cache@v4
-        with:
-          path: ./ack_backend/.venv
-          key: ${{ runner.os }}-venv-ack-py3.10-${{ hashFiles('ack_backend/poetry.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-venv-ack-py3.10-
-
-      - name: Cache Poetry virtualenv (delta_backend)
-        if: matrix.python-version == '3.11'
-        uses: actions/cache@v4
-        with:
-          path: ./delta_backend/.venv
-          key: ${{ runner.os }}-venv-delta-py3.11-${{ hashFiles('delta_backend/poetry.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-venv-delta-py3.11-
-
-      - name: Run unittest with filenameprocessor-coverage (S)
-        if: matrix.python-version == '3.10'
-        working-directory: filenameprocessor
-        id: filenameprocessor
-        continue-on-error: true
-        run: $RUN_TEST 3.10 filenameprocessor filenameprocessor-coverage.xml
-
-      - name: Run unittest with recordprocessor-coverage (s)
-        if: matrix.python-version == '3.10'
-        working-directory: recordprocessor
-        id: recordprocessor
-        continue-on-error: true
-        run: $RUN_TEST 3.10 recordprocessor recordprocessor-coverage.xml
-
-      - name: Run unittest with recordforwarder-coverage
-        if: matrix.python-version == '3.11'
-        working-directory: backend
-        id: recordforwarder
-        continue-on-error: true
-        run: |
-          poetry config virtualenvs.in-project true
-          $RUN_TEST 3.11 recordforwarder recordforwarder-coverage.xml
+      #   # This step is redundant - all of these tests will be run in the backend step below
+      # - name: Run unittest with recordforwarder-coverage
+      #   working-directory: backend
+      #   id: recordforwarder
+      #   continue-on-error: true
+      #   run: |
+      #     poetry env use 3.11
+      #     poetry install
+      #     poetry run coverage run -m unittest discover -s "./tests" -p "*batch*.py" || echo "recordforwarder tests failed" >> ../failed_tests.txt
+      #     poetry run coverage xml -o ../sonarcloud-coverage-recordforwarder-coverage.xml
 
       - name: Run unittest with coverage-ack-lambda
         if: matrix.python-version == '3.10'
         working-directory: ack_backend
         id: acklambda
         continue-on-error: true
-        run: $RUN_TEST 3.10 ack-lambda ack-lambda.xml
+        run: |
+          $RUN_TEST 3.10 "ack-lambda" "ack-lambda.xml"
 
       - name: Run unittest with coverage-delta
         if: matrix.python-version == '3.11'
@@ -129,7 +105,28 @@ jobs:
         env:
             PYTHONPATH: delta_backend/src:delta_backend/tests
         continue-on-error: true
-        run: $RUN_TEST 3.11 delta_backend delta.xml
+        run: |
+          $RUN_TEST 3.11 delta_backend delta.xml
+
+      # - name: Run unittest with coverage-fhir-api
+      #   working-directory: backend
+      #   id: fhirapi
+      #   continue-on-error: true
+      #   run: |
+      #     poetry env use 3.11
+      #     poetry install
+      #     poetry run coverage run -m unittest discover || echo "fhir-api tests failed" >> ../failed_tests.txt
+      #     poetry run coverage xml -o ../sonarcloud-coverage.xml
+
+      # - name: Run unittest with coverage-mesh-processor
+      #   working-directory: mesh_processor
+      #   id: meshprocessor
+      #   continue-on-error: true
+      #   run: |
+      #     poetry env use 3.10
+      #     poetry install
+      #     poetry run coverage run -m unittest discover || echo "mesh_processor tests failed" >> ../failed_tests.txt
+      #     poetry run coverage xml -o ../sonarcloud-mesh_processor-coverage.xml
 
       - name: Run Test Failure Summary
         id: check_failure
