indentation

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -129,10 +129,10 @@ jobs:
           PYTHONPATH: ${{ env.LAMBDA_PATH }}/mns_subscription/src:${{ env.SHARED_PATH }}/src
         continue-on-error: true
         run: |
-            poetry install
-            poetry run coverage run -m unittest discover || echo "mns_subscription tests failed" >> ../../failed_tests.txt
-            poetry run coverage report -m
-            poetry run coverage xml -o ../../mns_subscription-coverage.xml
+          poetry install
+          poetry run coverage run -m unittest discover || echo "mns_subscription tests failed" >> ../../failed_tests.txt
+          poetry run coverage report -m
+          poetry run coverage xml -o ../../mns_subscription-coverage.xml
 
       - name: Run unittest with redis_sync
         working-directory: lambdas/redis_sync
@@ -141,9 +141,9 @@ jobs:
           PYTHONPATH: ${{ env.LAMBDA_PATH }}/redis_sync/src:${{ env.SHARED_PATH }}/src
         continue-on-error: true
         run: |
-            poetry install
-            poetry run coverage run --source=src -m unittest discover || echo "redis_sync tests failed" >> ../../failed_tests.txt
-            poetry run coverage xml -o ../../redis_sync-coverage.xml
+          poetry install
+          poetry run coverage run --source=src -m unittest discover || echo "redis_sync tests failed" >> ../../failed_tests.txt
+          poetry run coverage xml -o ../../redis_sync-coverage.xml
 
       - name: Run unittest with shared
         working-directory: lambdas/shared
@@ -152,9 +152,9 @@ jobs:
           PYTHONPATH: ${{ env.SHARED_PATH }}/src
         continue-on-error: true
         run: |
-            poetry install
-            poetry run coverage run --rcfile=.coveragerc --source=src -m unittest discover -s tests -p "test_*.py" -v || echo "shared tests failed" >> ../../failed_tests.txt
-            poetry run coverage xml -o ../../shared-coverage.xml
+          poetry install
+          poetry run coverage run --rcfile=.coveragerc --source=src -m unittest discover -s tests -p "test_*.py" -v || echo "shared tests failed" >> ../../failed_tests.txt
+          poetry run coverage xml -o ../../shared-coverage.xml
 
       - name: Run unittest with id_sync
         working-directory: lambdas/id_sync
@@ -163,9 +163,9 @@ jobs:
           PYTHONPATH: ${{ env.LAMBDA_PATH }}/id_sync/src:${{ env.SHARED_PATH }}/src
         continue-on-error: true
         run: |
-            poetry install
-            poetry run coverage run --rcfile=.coveragerc --source=src -m unittest discover || echo "id_sync tests failed" >> ../../failed_tests.txt
-            poetry run coverage xml -o ../../id_sync-coverage.xml
+          poetry install
+          poetry run coverage run --rcfile=.coveragerc --source=src -m unittest discover || echo "id_sync tests failed" >> ../../failed_tests.txt
+          poetry run coverage xml -o ../../id_sync-coverage.xml
 
       - name: Run Test Failure Summary
         id: check_failure
