name

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -16,26 +16,16 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: make executable
-        run: |
-          echo "Making scripts executable:"
-          chmod +x $TEST_SCRIPT
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: List .github directory
         run: |
+          chmod +x $TEST_SCRIPT
+          chmod +x $SCRIPT_FOLDER/*.sh
           echo "Listing .github directory:"
-          ls -la ./.github
-
-      - name: List scripts directory
-        run: |
-          echo "Listing scripts directory:"
           ls -la ./.github/scripts
-          ls -la $SCRIPT_FOLDER
-
-      - name: List all subdirectories (including hidden)
-        run: |
-          echo "All subdirectories (including hidden):"
-          find . -type d
 
       - name: Check Script Path
         run: |
@@ -61,3 +51,105 @@ jobs:
       - name: Install poetry
         run: pip install poetry==1.8.4
 
+      - uses: actions/setup-python@v5
+        with:
+          python-version: |
+            3.10
+            3.11
+          cache: 'poetry'
+
+      - name: Set up AWS credentials
+        env:
+          AWS_ACCESS_KEY_ID: "FOOBARKEY"
+          AWS_SECRET_ACCESS_KEY: "FOOBARSECRET"
+        run: |
+          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
+
+      - name: Run unittest with filenameprocessor-coverage
+        working-directory: filenameprocessor
+        id: filenameprocessor
+        continue-on-error: true
+        run: |
+          $TEST_SCRIPT 3.10 \
+          "filenameprocessor" \
+          "sonarcloud-coverage-filenameprocessor-coverage.xml"
+
+      - name: Run unittest with recordprocessor-coverage
+        working-directory: recordprocessor
+        id: recordprocessor
+        continue-on-error: true
+        run: |
+          $TEST_SCRIPT 3.10 \
+          "recordprocessor" \
+          "sonarcloud-coverage-recordprocessor-coverage.xml"
+
+        # This step is redundant - all of these tests will be run in the backend step below
+      - name: Run unittest with recordforwarder-coverage
+        working-directory: backend
+        id: recordforwarder
+        continue-on-error: true
+        run: |
+          $TEST_SCRIPT 3.11 \
+          "recordforwarder" \
+          "sonarcloud-coverage-recordforwarder-coverage.xml"
+
+      - name: Run unittest with coverage-ack-lambda
+        working-directory: ack_backend
+        id: acklambda
+        continue-on-error: true
+        run: |
+          $TEST_SCRIPT 3.10 \
+          "ack-lambda" \
+          "sonarcloud-coverage-ack-lambda.xml"
+
+      - name: Run unittest with coverage-delta
+        working-directory: delta_backend
+        id: delta
+        env:
+            PYTHONPATH: delta_backend/src:delta_backend/tests
+        continue-on-error: true
+        run: |
+          $TEST_SCRIPT 3.11 \
+          "delta" \
+          "sonarcloud-coverage-delta.xml"
+
+      - name: Run unittest with coverage-fhir-api
+        working-directory: backend
+        id: fhirapi
+        continue-on-error: true
+        run: |
+          $TEST_SCRIPT 3.11 \
+          "fhir-api" \
+          "sonarcloud-coverage-fhir-api.xml"
+
+      - name: Run unittest with coverage-mesh-processor
+        working-directory: mesh_processor
+        id: meshprocessor
+        continue-on-error: true
+        run: |
+          $TEST_SCRIPT 3.10 \
+          "mesh_processor" \
+          "sonarcloud-coverage-mesh_processor-coverage.xml"
+
+      - name: Run Test Failure Summary
+        id: check_failure
+        run: |
+          if [ -s failed_tests.txt ]; then
+            echo "The following tests failed:"
+            cat failed_tests.txt
+
+            while IFS= read -r line; do
+              echo "##[error]Test Failures: $line"
+            done < failed_tests.txt
+
+            exit 1
+          else
+            echo "All tests passed."
+          fi
+
+      - name: SonarCloud Scan
+        uses: SonarSource/sonarqube-scan-action@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
