imline

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -6,9 +6,6 @@ on:
       - master
   pull_request:
     types: [labeled, opened, synchronize, reopened, unlabeled]
-env:
-  SCRIPT_FOLDER: ./.github/scripts
-  RUN_TEST: source ../.github/scripts/run_test.sh
 
 jobs:
   sonarcloud:
@@ -28,28 +25,8 @@ jobs:
 
       - uses: actions/setup-python@v5
         with:
-          python-version: |
-            3.10
-            3.11
+          python-version: ${{ matrix.python-version }}
           cache: 'poetry'
-
-      - name: Cache global Poetry virtualenvs
-
-        # uses: actions/cache@v4
-        # with:
-        #   path: ~/.cache/pypoetry/virtualenvs
-        #   key: ${{ runner.os }}-poetry-global-venv-py${{ matrix.python-version || 'all' }}-${{ hashFiles('**/poetry.lock') }}
-        #   restore-keys: |
-        #     ${{ runner.os }}-poetry-global-venv-py${{ matrix.python-version || 'all' }}-
-
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/pypoetry/virtualenvs
-          key: ${{ runner.os }}-poetry-venv-${{ matrix.python-version }}-${{ hashFiles('<project>/poetry.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-poetry-venv-${{ matrix.python-version }}-
-
-
 
       - name: Set up AWS credentials
         env:
@@ -69,44 +46,48 @@ jobs:
           poetry run coverage run -m unittest discover || echo "filenameprocessor tests failed" >> ../failed_tests.txt
           poetry run coverage xml -o ../sonarcloud-coverage-filenameprocessor-coverage.xml
 
-      # - name: Run unittest with recordprocessor-coverage
-      #   working-directory: recordprocessor
-      #   id: recordprocessor
-      #   continue-on-error: true
-      #   run: |
-      #     poetry env use 3.10
-      #     poetry install
-      #     poetry run coverage run -m unittest discover || echo "recordprocessor tests failed" >> ../failed_tests.txt
-      #     poetry run coverage xml -o ../sonarcloud-coverage-recordprocessor-coverage.xml
+      - name: Run unittest with recordprocessor-coverage
+        working-directory: recordprocessor
+        id: recordprocessor
+        continue-on-error: true
+        run: |
+          poetry env use 3.10
+          poetry install
+          poetry run coverage run -m unittest discover || echo "recordprocessor tests failed" >> ../failed_tests.txt
+          poetry run coverage xml -o ../sonarcloud-coverage-recordprocessor-coverage.xml
 
-      #   # This step is redundant - all of these tests will be run in the backend step below
-      # - name: Run unittest with recordforwarder-coverage
-      #   working-directory: backend
-      #   id: recordforwarder
-      #   continue-on-error: true
-      #   run: |
-      #     poetry env use 3.11
-      #     poetry install
-      #     poetry run coverage run -m unittest discover -s "./tests" -p "*batch*.py" || echo "recordforwarder tests failed" >> ../failed_tests.txt
-      #     poetry run coverage xml -o ../sonarcloud-coverage-recordforwarder-coverage.xml
+        # This step is redundant - all of these tests will be run in the backend step below
+      - name: Run unittest with recordforwarder-coverage
+        working-directory: backend
+        id: recordforwarder
+        continue-on-error: true
+        run: |
+          poetry env use 3.11
+          poetry install
+          poetry run coverage run -m unittest discover -s "./tests" -p "*batch*.py" || echo "recordforwarder tests failed" >> ../failed_tests.txt
+          poetry run coverage xml -o ../sonarcloud-coverage-recordforwarder-coverage.xml
 
       - name: Run unittest with coverage-ack-lambda
-        if: matrix.python-version == '3.10'
         working-directory: ack_backend
         id: acklambda
         continue-on-error: true
         run: |
-          $RUN_TEST 3.10 "ack-lambda" "ack-lambda.xml"
+          poetry env use 3.10
+          poetry install
+          poetry run coverage run -m unittest discover || echo "ack-lambda tests failed" >> ../failed_tests.txt
+          poetry run coverage xml -o ../sonarcloud-coverage-ack-lambda.xml
 
       - name: Run unittest with coverage-delta
-        if: matrix.python-version == '3.11'
         working-directory: delta_backend
         id: delta
         env:
             PYTHONPATH: delta_backend/src:delta_backend/tests
         continue-on-error: true
         run: |
-          $RUN_TEST 3.11 delta_backend delta.xml
+          poetry env use 3.11
+          poetry install
+          poetry run coverage run -m unittest discover || echo "delta tests failed" >> ../failed_tests.txt
+          poetry run coverage xml -o ../sonarcloud-coverage-delta.xml
 
       - name: Run unittest with coverage-fhir-api
         working-directory: backend
@@ -118,15 +99,15 @@ jobs:
           poetry run coverage run -m unittest discover || echo "fhir-api tests failed" >> ../failed_tests.txt
           poetry run coverage xml -o ../sonarcloud-coverage.xml
 
-      # - name: Run unittest with coverage-mesh-processor
-      #   working-directory: mesh_processor
-      #   id: meshprocessor
-      #   continue-on-error: true
-      #   run: |
-      #     poetry env use 3.10
-      #     poetry install
-      #     poetry run coverage run -m unittest discover || echo "mesh_processor tests failed" >> ../failed_tests.txt
-      #     poetry run coverage xml -o ../sonarcloud-mesh_processor-coverage.xml
+      - name: Run unittest with coverage-mesh-processor
+        working-directory: mesh_processor
+        id: meshprocessor
+        continue-on-error: true
+        run: |
+          poetry env use 3.10
+          poetry install
+          poetry run coverage run -m unittest discover || echo "mesh_processor tests failed" >> ../failed_tests.txt
+          poetry run coverage xml -o ../sonarcloud-mesh_processor-coverage.xml
 
       - name: Run Test Failure Summary
         id: check_failure
