debug error

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -30,6 +30,11 @@ jobs:
             3.10
             3.11
           cache: 'poetry'
+      - name: Debug shared folder
+        run: |
+          echo "Showing shared/src/common structure:"
+          ls
+          ls -R lambdas/shared/src/common || echo "Directory missing"
 
       - name: Set up AWS credentials
         env:
